export const aboutStyles = {
  section: { py: 8 },
  mainTitle: {
    fontSize: { xs: '2rem', md: '3rem' },
    fontWeight: 700,
    mb: 4,
    textAlign: 'center',
  },
  description: {
    mb: 6,
    maxWidth: '800px',
    mx: 'auto',
    textAlign: 'center',
  },
  sectionTitle: {
    fontSize: { xs: '1.5rem', md: '2rem' },
    fontWeight: 600,
    mb: 3,
  },
  educationGrid: { mb: 6 },
  educationPaper: {
    p: 3,
    height: '100%',
    background: '#ffffff',
    borderRadius: '20px',
    overflow: 'hidden',
    position: 'relative',
    border: '1px solid #e2e8f0',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    transition: 'all 0.3s ease-in-out',
    '&:hover': {
      transform: 'translateY(-5px)',
      boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      background: 'linear-gradient(to bottom right, #ffffff, #f8fafc)',
    },
  },
  decorativeCircle: (gradient) => ({
    position: 'absolute',
    borderRadius: '50%',
    background: gradient,
    opacity: 0.05,
  }),
  decorativeCircles: {
    topRight: {
      top: 20,
      right: 20,
      width: 60,
      height: 60,
    },
    bottomRight: {
      bottom: 30,
      right: 40,
      width: 40,
      height: 40,
    },
    topRightSmall: {
      top: 60,
      right: 90,
      width: 30,
      height: 30,
    },
    bottomRightMedium: {
      bottom: 50,
      right: 100,
      width: 45,
      height: 45,
    },
  },
  degreeTitle: {
    fontWeight: 700,
    mb: 2,
    color: '#1a365d',
    background: 'linear-gradient(90deg, #1a365d 0%, #2c5282 100%)',
    WebkitBackgroundClip: 'text',
    WebkitTextFillColor: 'transparent',
  },
  infoContainer: {
    display: 'flex',
    alignItems: 'center',
    mb: 2,
  },
  icon: {
    mr: 1.5,
    color: '#4a5568',
    fontSize: 22,
  },
  schoolText: {
    color: '#2d3748',
    fontWeight: 500,
  },
  infoText: {
    color: '#4a5568',
  },
  skillPaper: {
    p: 3,
    height: '100%',
    background: '#ffffff',
    borderRadius: '20px',
    position: 'relative',
    overflow: 'hidden',
    border: '1px solid #e2e8f0',
    boxShadow: '0 4px 6px -1px rgba(0, 0, 0, 0.1), 0 2px 4px -1px rgba(0, 0, 0, 0.06)',
    transition: 'all 0.3s ease-in-out',
    '&:hover': {
      transform: 'translateY(-5px)',
      boxShadow: '0 20px 25px -5px rgba(0, 0, 0, 0.1), 0 10px 10px -5px rgba(0, 0, 0, 0.04)',
      background: 'linear-gradient(to bottom right, #ffffff, #f8fafc)',
    },
  },
  skillHeader: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: '4px',
  },
  skillIconContainer: {
    width: 60,
    height: 60,
    borderRadius: '15px',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    color: '#4a5568',
    fontSize: 22,
  },
  skillTitle: {
    fontWeight: 600,
    color: '#2c3e50',
  },
  skillChipsContainer: {
    display: 'flex',
    flexWrap: 'wrap',
    gap: 1,
  },
  skillChip: {
    borderRadius: '12px',
    background: '#f1f5f9',
    color: '#334155',
    border: '1px solid #cbd5e1',
    fontWeight: 500,
    py: 0.5,
    '&:hover': {
      background: '#e2e8f0',
      transform: 'scale(1.05)',
      boxShadow: '0 2px 4px rgba(0,0,0,0.05)',
    },
    transition: 'all 0.2s ease-in-out',
  },
};
